name: Cloud Storage Upload

on:
  push:
    branches: ["master"]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - id: "checkout"
        uses: actions/checkout@v4

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.FirebaseProject }}

      - name: "Upload posts directory"
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: "/posts"
          destination: "gs://marcosdly-personal-website.appspot.com/blog"
          glob: "**/*.md"
